- hosts: localhost
  connection: local
  tasks:
    - name: Check or install uv
      block:
      - name: Check if uv is installed
        shell: |
          uv --version
        register: "check_uv"
      rescue:
      - name: Install uv with pip
        shell: |
          pip install --upgrade uv
        register: "install_uv"
      always:
      - name: About uv
        shell: |
          uv --version
        register: "about_uv"
    - debug: var=check_uv.stdout_lines
    - debug: var=install_uv.stdout_lines
    - debug: var=about_uv.stdout_lines
