/* File: iriwebmodule.c
 * This file is auto-generated with f2py (version:2.2.6).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * Generation date: Fri Feb 20 19:21:28 2026
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

#ifndef PY_SSIZE_T_CLEAN
#define PY_SSIZE_T_CLEAN
#endif /* PY_SSIZE_T_CLEAN */

/* Unconditionally included */
#include <Python.h>
#include <numpy/npy_os.h>

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "fortranobject.h"
/*need_includes0*/

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *iriweb_error;
static PyObject *iriweb_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
/*need_typedefs*/

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/

#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif


/* See fortranobject.h for definitions. The macros here are provided for BC. */
#define rank f2py_rank
#define shape f2py_shape
#define fshape f2py_shape
#define len f2py_len
#define flen f2py_flen
#define slen f2py_slen
#define size f2py_size


#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
    PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
    fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif


#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif


/************************ See f2py2e/cfuncs.py: cfuncs ************************/

static int
double_from_pyobj(double* v, PyObject *obj, const char *errmess)
{
    PyObject* tmp = NULL;
    if (PyFloat_Check(obj)) {
        *v = PyFloat_AsDouble(obj);
        return !(*v == -1.0 && PyErr_Occurred());
    }

    tmp = PyNumber_Float(obj);
    if (tmp) {
        *v = PyFloat_AsDouble(tmp);
        Py_DECREF(tmp);
        return !(*v == -1.0 && PyErr_Occurred());
    }

    if (PyComplex_Check(obj)) {
        PyErr_Clear();
        tmp = PyObject_GetAttrString(obj,"real");
    }
    else if (PyBytes_Check(obj) || PyUnicode_Check(obj)) {
        /*pass*/;
    }
    else if (PySequence_Check(obj)) {
        PyErr_Clear();
        tmp = PySequence_GetItem(obj, 0);
    }

    if (tmp) {
        if (double_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
        Py_DECREF(tmp);
    }
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = iriweb_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}


static int
float_from_pyobj(float* v, PyObject *obj, const char *errmess)
{
    double d=0.0;
    if (double_from_pyobj(&d,obj,errmess)) {
        *v = (float)d;
        return 1;
    }
    return 0;
}


static int
int_from_pyobj(int* v, PyObject *obj, const char *errmess)
{
    PyObject* tmp = NULL;

    if (PyLong_Check(obj)) {
        *v = Npy__PyLong_AsInt(obj);
        return !(*v == -1 && PyErr_Occurred());
    }

    tmp = PyNumber_Long(obj);
    if (tmp) {
        *v = Npy__PyLong_AsInt(tmp);
        Py_DECREF(tmp);
        return !(*v == -1 && PyErr_Occurred());
    }

    if (PyComplex_Check(obj)) {
        PyErr_Clear();
        tmp = PyObject_GetAttrString(obj,"real");
    }
    else if (PyBytes_Check(obj) || PyUnicode_Check(obj)) {
        /*pass*/;
    }
    else if (PySequence_Check(obj)) {
        PyErr_Clear();
        tmp = PySequence_GetItem(obj, 0);
    }

    if (tmp) {
        if (int_from_pyobj(v, tmp, errmess)) {
            Py_DECREF(tmp);
            return 1;
        }
        Py_DECREF(tmp);
    }

    {
        PyObject* err = PyErr_Occurred();
        if (err == NULL) {
            err = iriweb_error;
        }
        PyErr_SetString(err, errmess);
    }
    return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void F_FUNC(iriwebg,IRIWEBG)(float*,float*,float*,int*,int*,float*,float*,float*,float*,float*,float*,float*,int*,int*,int*,int*,float*);
extern void F_FUNC(iritec,IRITEC)(float*,float*,float*,int*,int*,float*,float*,float*,float*,float*,float*,float*,int*,int*,int*,int*,float*);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/********************************** iriwebg **********************************/
static char doc_f2py_rout_iriweb_iriwebg[] = "\
iriwebg(jf,alat,along,iyear,mmdd,slt,glat,glong,stl,f107d,f107,ap,iap,ssn,ig,sax,sday)\n\nWrapper for ``iriwebg``.\
\n\nParameters\n----------\n"
"jf : input rank-1 array('f') with bounds (30)\n"
"alat : input float\n"
"along : input float\n"
"iyear : input int\n"
"mmdd : input int\n"
"slt : input float\n"
"glat : input float\n"
"glong : input float\n"
"stl : input float\n"
"f107d : input float\n"
"f107 : input float\n"
"ap : input float\n"
"iap : input int\n"
"ssn : input int\n"
"ig : input int\n"
"sax : input int\n"
"sday : input float";
/* extern void F_FUNC(iriwebg,IRIWEBG)(float*,float*,float*,int*,int*,float*,float*,float*,float*,float*,float*,float*,int*,int*,int*,int*,float*); */
static PyObject *f2py_rout_iriweb_iriwebg(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(float*,float*,float*,int*,int*,float*,float*,float*,float*,float*,float*,float*,int*,int*,int*,int*,float*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    float *jf = NULL;
    npy_intp jf_Dims[1] = {-1};
    const int jf_Rank = 1;
    PyArrayObject *capi_jf_as_array = NULL;
    int capi_jf_intent = 0;
    PyObject *jf_capi = Py_None;
    float alat = 0;
    PyObject *alat_capi = Py_None;
    float along = 0;
    PyObject *along_capi = Py_None;
    int iyear = 0;
    PyObject *iyear_capi = Py_None;
    int mmdd = 0;
    PyObject *mmdd_capi = Py_None;
    float slt = 0;
    PyObject *slt_capi = Py_None;
    float glat = 0;
    PyObject *glat_capi = Py_None;
    float glong = 0;
    PyObject *glong_capi = Py_None;
    float stl = 0;
    PyObject *stl_capi = Py_None;
    float f107d = 0;
    PyObject *f107d_capi = Py_None;
    float f107 = 0;
    PyObject *f107_capi = Py_None;
    float ap = 0;
    PyObject *ap_capi = Py_None;
    int iap = 0;
    PyObject *iap_capi = Py_None;
    int ssn = 0;
    PyObject *ssn_capi = Py_None;
    int ig = 0;
    PyObject *ig_capi = Py_None;
    int sax = 0;
    PyObject *sax_capi = Py_None;
    float sday = 0;
    PyObject *sday_capi = Py_None;
    static char *capi_kwlist[] = {"jf","alat","along","iyear","mmdd","slt","glat","glong","stl","f107d","f107","ap","iap","ssn","ig","sax","sday",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOOOOOOOOOOOOOOOO|:iriweb.iriwebg",\
        capi_kwlist,&jf_capi,&alat_capi,&along_capi,&iyear_capi,&mmdd_capi,&slt_capi,&glat_capi,&glong_capi,&stl_capi,&f107d_capi,&f107_capi,&ap_capi,&iap_capi,&ssn_capi,&ig_capi,&sax_capi,&sday_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable jf */
    jf_Dims[0]=30;
    capi_jf_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "iriweb.iriweb.iriwebg: failed to create array from the 1st argument `jf`";
    capi_jf_as_array = ndarray_from_pyobj(  NPY_FLOAT,1,jf_Dims,jf_Rank,  capi_jf_intent,jf_capi,capi_errmess);
    if (capi_jf_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = iriweb_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        jf = (float *)(PyArray_DATA(capi_jf_as_array));

    /* Processing variable alat */
        f2py_success = float_from_pyobj(&alat,alat_capi,"iriweb.iriwebg() 2nd argument (alat) can't be converted to float");
    if (f2py_success) {
    /* Processing variable along */
        f2py_success = float_from_pyobj(&along,along_capi,"iriweb.iriwebg() 3rd argument (along) can't be converted to float");
    if (f2py_success) {
    /* Processing variable iyear */
        f2py_success = int_from_pyobj(&iyear,iyear_capi,"iriweb.iriwebg() 4th argument (iyear) can't be converted to int");
    if (f2py_success) {
    /* Processing variable mmdd */
        f2py_success = int_from_pyobj(&mmdd,mmdd_capi,"iriweb.iriwebg() 5th argument (mmdd) can't be converted to int");
    if (f2py_success) {
    /* Processing variable slt */
        f2py_success = float_from_pyobj(&slt,slt_capi,"iriweb.iriwebg() 6th argument (slt) can't be converted to float");
    if (f2py_success) {
    /* Processing variable glat */
        f2py_success = float_from_pyobj(&glat,glat_capi,"iriweb.iriwebg() 7th argument (glat) can't be converted to float");
    if (f2py_success) {
    /* Processing variable glong */
        f2py_success = float_from_pyobj(&glong,glong_capi,"iriweb.iriwebg() 8th argument (glong) can't be converted to float");
    if (f2py_success) {
    /* Processing variable stl */
        f2py_success = float_from_pyobj(&stl,stl_capi,"iriweb.iriwebg() 9th argument (stl) can't be converted to float");
    if (f2py_success) {
    /* Processing variable f107d */
        f2py_success = float_from_pyobj(&f107d,f107d_capi,"iriweb.iriwebg() 10th argument (f107d) can't be converted to float");
    if (f2py_success) {
    /* Processing variable f107 */
        f2py_success = float_from_pyobj(&f107,f107_capi,"iriweb.iriwebg() 11st argument (f107) can't be converted to float");
    if (f2py_success) {
    /* Processing variable ap */
        f2py_success = float_from_pyobj(&ap,ap_capi,"iriweb.iriwebg() 12nd argument (ap) can't be converted to float");
    if (f2py_success) {
    /* Processing variable iap */
        f2py_success = int_from_pyobj(&iap,iap_capi,"iriweb.iriwebg() 13rd argument (iap) can't be converted to int");
    if (f2py_success) {
    /* Processing variable ssn */
        f2py_success = int_from_pyobj(&ssn,ssn_capi,"iriweb.iriwebg() 14th argument (ssn) can't be converted to int");
    if (f2py_success) {
    /* Processing variable ig */
        f2py_success = int_from_pyobj(&ig,ig_capi,"iriweb.iriwebg() 15th argument (ig) can't be converted to int");
    if (f2py_success) {
    /* Processing variable sax */
        f2py_success = int_from_pyobj(&sax,sax_capi,"iriweb.iriwebg() 16th argument (sax) can't be converted to int");
    if (f2py_success) {
    /* Processing variable sday */
        f2py_success = float_from_pyobj(&sday,sday_capi,"iriweb.iriwebg() 17th argument (sday) can't be converted to float");
    if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)(jf,&alat,&along,&iyear,&mmdd,&slt,&glat,&glong,&stl,&f107d,&f107,&ap,&iap,&ssn,&ig,&sax,&sday);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    } /*if (f2py_success) of sday*/
    /* End of cleaning variable sday */
    } /*if (f2py_success) of sax*/
    /* End of cleaning variable sax */
    } /*if (f2py_success) of ig*/
    /* End of cleaning variable ig */
    } /*if (f2py_success) of ssn*/
    /* End of cleaning variable ssn */
    } /*if (f2py_success) of iap*/
    /* End of cleaning variable iap */
    } /*if (f2py_success) of ap*/
    /* End of cleaning variable ap */
    } /*if (f2py_success) of f107*/
    /* End of cleaning variable f107 */
    } /*if (f2py_success) of f107d*/
    /* End of cleaning variable f107d */
    } /*if (f2py_success) of stl*/
    /* End of cleaning variable stl */
    } /*if (f2py_success) of glong*/
    /* End of cleaning variable glong */
    } /*if (f2py_success) of glat*/
    /* End of cleaning variable glat */
    } /*if (f2py_success) of slt*/
    /* End of cleaning variable slt */
    } /*if (f2py_success) of mmdd*/
    /* End of cleaning variable mmdd */
    } /*if (f2py_success) of iyear*/
    /* End of cleaning variable iyear */
    } /*if (f2py_success) of along*/
    /* End of cleaning variable along */
    } /*if (f2py_success) of alat*/
    /* End of cleaning variable alat */
    if((PyObject *)capi_jf_as_array!=jf_capi) {
        Py_XDECREF(capi_jf_as_array); }
    }  /* if (capi_jf_as_array == NULL) ... else of jf */
    /* End of cleaning variable jf */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/******************************* end of iriwebg *******************************/

/*********************************** iritec ***********************************/
static char doc_f2py_rout_iriweb_iritec[] = "\
iritec(jf,alat,along,iyear,mmdd,slt,glat,glong,stl,f107d,f107,ap,iap,ssn,ig,sax,sday)\n\nWrapper for ``iritec``.\
\n\nParameters\n----------\n"
"jf : input rank-1 array('f') with bounds (30)\n"
"alat : input float\n"
"along : input float\n"
"iyear : input int\n"
"mmdd : input int\n"
"slt : input float\n"
"glat : input float\n"
"glong : input float\n"
"stl : input float\n"
"f107d : input float\n"
"f107 : input float\n"
"ap : input float\n"
"iap : input int\n"
"ssn : input int\n"
"ig : input int\n"
"sax : input int\n"
"sday : input float";
/* extern void F_FUNC(iritec,IRITEC)(float*,float*,float*,int*,int*,float*,float*,float*,float*,float*,float*,float*,int*,int*,int*,int*,float*); */
static PyObject *f2py_rout_iriweb_iritec(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(float*,float*,float*,int*,int*,float*,float*,float*,float*,float*,float*,float*,int*,int*,int*,int*,float*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    float *jf = NULL;
    npy_intp jf_Dims[1] = {-1};
    const int jf_Rank = 1;
    PyArrayObject *capi_jf_as_array = NULL;
    int capi_jf_intent = 0;
    PyObject *jf_capi = Py_None;
    float alat = 0;
    PyObject *alat_capi = Py_None;
    float along = 0;
    PyObject *along_capi = Py_None;
    int iyear = 0;
    PyObject *iyear_capi = Py_None;
    int mmdd = 0;
    PyObject *mmdd_capi = Py_None;
    float slt = 0;
    PyObject *slt_capi = Py_None;
    float glat = 0;
    PyObject *glat_capi = Py_None;
    float glong = 0;
    PyObject *glong_capi = Py_None;
    float stl = 0;
    PyObject *stl_capi = Py_None;
    float f107d = 0;
    PyObject *f107d_capi = Py_None;
    float f107 = 0;
    PyObject *f107_capi = Py_None;
    float ap = 0;
    PyObject *ap_capi = Py_None;
    int iap = 0;
    PyObject *iap_capi = Py_None;
    int ssn = 0;
    PyObject *ssn_capi = Py_None;
    int ig = 0;
    PyObject *ig_capi = Py_None;
    int sax = 0;
    PyObject *sax_capi = Py_None;
    float sday = 0;
    PyObject *sday_capi = Py_None;
    static char *capi_kwlist[] = {"jf","alat","along","iyear","mmdd","slt","glat","glong","stl","f107d","f107","ap","iap","ssn","ig","sax","sday",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOOOOOOOOOOOOOOOO|:iriweb.iritec",\
        capi_kwlist,&jf_capi,&alat_capi,&along_capi,&iyear_capi,&mmdd_capi,&slt_capi,&glat_capi,&glong_capi,&stl_capi,&f107d_capi,&f107_capi,&ap_capi,&iap_capi,&ssn_capi,&ig_capi,&sax_capi,&sday_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable jf */
    jf_Dims[0]=30;
    capi_jf_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "iriweb.iriweb.iritec: failed to create array from the 1st argument `jf`";
    capi_jf_as_array = ndarray_from_pyobj(  NPY_FLOAT,1,jf_Dims,jf_Rank,  capi_jf_intent,jf_capi,capi_errmess);
    if (capi_jf_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = iriweb_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        jf = (float *)(PyArray_DATA(capi_jf_as_array));

    /* Processing variable alat */
        f2py_success = float_from_pyobj(&alat,alat_capi,"iriweb.iritec() 2nd argument (alat) can't be converted to float");
    if (f2py_success) {
    /* Processing variable along */
        f2py_success = float_from_pyobj(&along,along_capi,"iriweb.iritec() 3rd argument (along) can't be converted to float");
    if (f2py_success) {
    /* Processing variable iyear */
        f2py_success = int_from_pyobj(&iyear,iyear_capi,"iriweb.iritec() 4th argument (iyear) can't be converted to int");
    if (f2py_success) {
    /* Processing variable mmdd */
        f2py_success = int_from_pyobj(&mmdd,mmdd_capi,"iriweb.iritec() 5th argument (mmdd) can't be converted to int");
    if (f2py_success) {
    /* Processing variable slt */
        f2py_success = float_from_pyobj(&slt,slt_capi,"iriweb.iritec() 6th argument (slt) can't be converted to float");
    if (f2py_success) {
    /* Processing variable glat */
        f2py_success = float_from_pyobj(&glat,glat_capi,"iriweb.iritec() 7th argument (glat) can't be converted to float");
    if (f2py_success) {
    /* Processing variable glong */
        f2py_success = float_from_pyobj(&glong,glong_capi,"iriweb.iritec() 8th argument (glong) can't be converted to float");
    if (f2py_success) {
    /* Processing variable stl */
        f2py_success = float_from_pyobj(&stl,stl_capi,"iriweb.iritec() 9th argument (stl) can't be converted to float");
    if (f2py_success) {
    /* Processing variable f107d */
        f2py_success = float_from_pyobj(&f107d,f107d_capi,"iriweb.iritec() 10th argument (f107d) can't be converted to float");
    if (f2py_success) {
    /* Processing variable f107 */
        f2py_success = float_from_pyobj(&f107,f107_capi,"iriweb.iritec() 11st argument (f107) can't be converted to float");
    if (f2py_success) {
    /* Processing variable ap */
        f2py_success = float_from_pyobj(&ap,ap_capi,"iriweb.iritec() 12nd argument (ap) can't be converted to float");
    if (f2py_success) {
    /* Processing variable iap */
        f2py_success = int_from_pyobj(&iap,iap_capi,"iriweb.iritec() 13rd argument (iap) can't be converted to int");
    if (f2py_success) {
    /* Processing variable ssn */
        f2py_success = int_from_pyobj(&ssn,ssn_capi,"iriweb.iritec() 14th argument (ssn) can't be converted to int");
    if (f2py_success) {
    /* Processing variable ig */
        f2py_success = int_from_pyobj(&ig,ig_capi,"iriweb.iritec() 15th argument (ig) can't be converted to int");
    if (f2py_success) {
    /* Processing variable sax */
        f2py_success = int_from_pyobj(&sax,sax_capi,"iriweb.iritec() 16th argument (sax) can't be converted to int");
    if (f2py_success) {
    /* Processing variable sday */
        f2py_success = float_from_pyobj(&sday,sday_capi,"iriweb.iritec() 17th argument (sday) can't be converted to float");
    if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)(jf,&alat,&along,&iyear,&mmdd,&slt,&glat,&glong,&stl,&f107d,&f107,&ap,&iap,&ssn,&ig,&sax,&sday);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    } /*if (f2py_success) of sday*/
    /* End of cleaning variable sday */
    } /*if (f2py_success) of sax*/
    /* End of cleaning variable sax */
    } /*if (f2py_success) of ig*/
    /* End of cleaning variable ig */
    } /*if (f2py_success) of ssn*/
    /* End of cleaning variable ssn */
    } /*if (f2py_success) of iap*/
    /* End of cleaning variable iap */
    } /*if (f2py_success) of ap*/
    /* End of cleaning variable ap */
    } /*if (f2py_success) of f107*/
    /* End of cleaning variable f107 */
    } /*if (f2py_success) of f107d*/
    /* End of cleaning variable f107d */
    } /*if (f2py_success) of stl*/
    /* End of cleaning variable stl */
    } /*if (f2py_success) of glong*/
    /* End of cleaning variable glong */
    } /*if (f2py_success) of glat*/
    /* End of cleaning variable glat */
    } /*if (f2py_success) of slt*/
    /* End of cleaning variable slt */
    } /*if (f2py_success) of mmdd*/
    /* End of cleaning variable mmdd */
    } /*if (f2py_success) of iyear*/
    /* End of cleaning variable iyear */
    } /*if (f2py_success) of along*/
    /* End of cleaning variable along */
    } /*if (f2py_success) of alat*/
    /* End of cleaning variable alat */
    if((PyObject *)capi_jf_as_array!=jf_capi) {
        Py_XDECREF(capi_jf_as_array); }
    }  /* if (capi_jf_as_array == NULL) ... else of jf */
    /* End of cleaning variable jf */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/******************************* end of iritec *******************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
    {"iriwebg",-1,{{-1}},0,0,(char *)  F_FUNC(iriwebg,IRIWEBG),  (f2py_init_func)f2py_rout_iriweb_iriwebg,doc_f2py_rout_iriweb_iriwebg},
    {"iritec",-1,{{-1}},0,0,(char *)  F_FUNC(iritec,IRITEC),  (f2py_init_func)f2py_rout_iriweb_iritec,doc_f2py_rout_iriweb_iritec},

/*eof routine_defs*/
    {NULL}
};

static PyMethodDef f2py_module_methods[] = {

    {NULL,NULL}
};

static struct PyModuleDef moduledef = {
    PyModuleDef_HEAD_INIT,
    "iriweb",
    NULL,
    -1,
    f2py_module_methods,
    NULL,
    NULL,
    NULL,
    NULL
};

PyMODINIT_FUNC PyInit_iriweb(void) {
    int i;
    PyObject *m,*d, *s, *tmp;
    m = iriweb_module = PyModule_Create(&moduledef);
    Py_SET_TYPE(&PyFortran_Type, &PyType_Type);
    import_array();
    if (PyErr_Occurred())
        {PyErr_SetString(PyExc_ImportError, "can't initialize module iriweb (failed to import numpy)"); return m;}
    d = PyModule_GetDict(m);
    s = PyUnicode_FromString("2.2.6");
    PyDict_SetItemString(d, "__version__", s);
    Py_DECREF(s);
    s = PyUnicode_FromString(
        "This module 'iriweb' is auto-generated with f2py (version:2.2.6).\nFunctions:\n"
"    iriwebg(jf,alat,along,iyear,mmdd,slt,glat,glong,stl,f107d,f107,ap,iap,ssn,ig,sax,sday)\n"
"    iritec(jf,alat,along,iyear,mmdd,slt,glat,glong,stl,f107d,f107,ap,iap,ssn,ig,sax,sday)\n"
".");
    PyDict_SetItemString(d, "__doc__", s);
    Py_DECREF(s);
    s = PyUnicode_FromString("2.2.6");
    PyDict_SetItemString(d, "__f2py_numpy_version__", s);
    Py_DECREF(s);
    iriweb_error = PyErr_NewException ("iriweb.error", NULL, NULL);
    /*
     * Store the error object inside the dict, so that it could get deallocated.
     * (in practice, this is a module, so it likely will not and cannot.)
     */
    PyDict_SetItemString(d, "_iriweb_error", iriweb_error);
    Py_DECREF(iriweb_error);
    for(i=0;f2py_routine_defs[i].name!=NULL;i++) {
        tmp = PyFortranObject_NewAsAttr(&f2py_routine_defs[i]);
        PyDict_SetItemString(d, f2py_routine_defs[i].name, tmp);
        Py_DECREF(tmp);
    }


/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#if Py_GIL_DISABLED
    // signal whether this module supports running with the GIL disabled
    PyUnstable_Module_SetGIL(m , Py_MOD_GIL_USED);
#endif

#ifdef F2PY_REPORT_ATEXIT
    if (! PyErr_Occurred())
        on_exit(f2py_report_on_exit,(void*)"iriweb");
#endif

    if (PyType_Ready(&PyFortran_Type) < 0) {
        return NULL;
    }

    return m;
}
#ifdef __cplusplus
}
#endif
